flask_proj/blog/core/views.py
from flask import render_template,Blueprint

core = Blueprint('core',__name__)


@core.route('/')
def index():
    return render_template('index.html')

flask_proj/blog/templates/account.html
{% extends "base.html" %}
{% from "helpers/_formhelpers.html" import render_field %}

{% block body %}

<div class="container-fluid">

<h1>Welcome to the page for {{current_user.username}}</h1>
<img src="{{profile_image}}" alt="" >
<form method=post enctype="multipart/form-data">
    <dl>
      {{form.hidden_tag()}}
      {{ render_field(form.email) }}
      {{ render_field(form.username) }}
<br>
      <input class="btn btn-success" type="submit" value="Submit">
    </dl>
    
  </form>

</div>


{% endblock  %}

flask_proj/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{{url_for('core.index')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Features</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Pricing</a>
            </li>   
          </ul>
        </div>
      </nav>

    {% block body %}

    {% endblock %}




</body>
</html>

flask_proj/blog/templates/index.html
{% extends "base.html" %}

{% block body %}

<div class="container">

    <div class="jumbotron">
        <h1>'  Welcome to the Witcher Universe !!!!'</h1>
        <img src="{{url_for('static',filename='960x0.jpg')}}" alt="">

    </div>
</div>


{% endblock  %}

flask_proj/blog/templates/login.html
{% extends "base.html" %}
{% from "helpers/_formhelpers.html" import render_field %}

{% block body %}

<div class="container">
<form method=post>
  <dl>
  {{form.hidden_tag()}}
    {{ render_field(form.email) }}

    {{ render_field(form.password) }} <br>
    <input class="btn btn-success" type="submit" value="Submit">
  </dl>
  
</form>

</div>


{% endblock  %}

flask_proj/blog/templates/register.html
{% extends "base.html" %}
{% from "helpers/_formhelpers.html" import render_field %}

{% block body %}

<div class="container">
<form method=post>
  <dl>
  {{form.hidden_tag()}}
    {{ render_field(form.email) }}
    {{ render_field(form.username) }}
    {{ render_field(form.password) }}
    {{ render_field(form.pass_confirm) }} <br>
    <input class="btn btn-success" type="submit" value="Submit">
  </dl>
  
</form>

</div>


{% endblock  %}

flask_proj/blog/templates/user_blog_posts.html
{% extends "base.html" %}

{% block body %}

<div class="container">

<div class="jumbotron">

<h1>Welcome to the page for {{user.username}}</h1>
<img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}" alt="">


</div>


    {% for post in blog_post.items %}

    <h2><a href="{{url_for('blog_posts.blog_post',blog_post_id=post.id)}}">{{post.title}}</a></h2>
    <small>Written by : <a href="#">{{post.author.username}}</a></small>

    {% endfor %}

</div>

{% endblock  %}